#!/bin/sh -e

# Change the order for checking installed compilers as
# the ccache clang symlink might exist, but clang might not be installed.
sed 's/clang gcc cc/cc clang gcc/g' icu4c/source/configure > _
mv -f _ icu4c/source/configure
sed 's/clang++ g++ c++/c++ clang++ g++/g' icu4c/source/configure > _
mv -f _ icu4c/source/configure

sh icu4c/source/configure \
    --prefix=/usr \
    --sbindir=/usr/bin

make
make DESTDIR="$1" install
