#!/bin/sh -e

mkdir -m 755 \
    "$1/Data" \
    "$1/Data/Kiss" \
    "$1/Data/Kiss/Repo" \
    "$1/Kernel" \
    "$1/Kernel/Boot" \
    "$1/dev" \
    "$1/etc" \
    "$1/Users" \
    "$1/Mount" \
    "$1/run" \
    "$1/bin" \
    "$1/include" \
    "$1/lib" \
    "$1/share" \
    "$1/share/man" \
    "$1/share/man/man1" \
    "$1/share/man/man2" \
    "$1/share/man/man3" \
    "$1/share/man/man4" \
    "$1/share/man/man5" \
    "$1/share/man/man6" \
    "$1/share/man/man7" \
    "$1/share/man/man8" \
    "$1/var/cache" \
    "$1/var/local" \
    "$1/var/opt" \
    "$1/var/log" \
    "$1/var/log/old" \
    "$1/var/lib" \
    "$1/var/lib/misc" \
    "$1/var/empty" \
    "$1/var/service" \
    "$1/var/spool"

mkdir -m 555 \
    "$1/proc" \
    "$1/sys"

mkdir -m 0750 \
    "$1/Users/root"

mkdir -m 1777 \
    "$1/tmp" \
    "$1/var/tmp" \
    "$1/var/spool/mail"

ln -sf bin "$1/sbin"
ln -sf lib "$1/lib64"
ln -sf .   "$1/usr"

ln -sf spool/mail        "$1/var/mail"
ln -sf ../run            "$1/var/run"
ln -sf ../run/lock       "$1/var/lock"
ln -sf /proc/self/mounts "$1/etc/mtab"

cp -f ./* "$1/etc"

chmod 600 \
    "$1/etc/crypttab" \
    "$1/etc/shadow"
