#!/bin/sh -e

./configure \
    --prefix=/usr \
    --with-included-popt \
    --disable-xxhash \
    --disable-zstd \
    --disable-lz4 \
    --disable-openssl \
    --without-included-zlib

make
make DESTDIR="$1" install
