pipeline:
  build:
    image: alpine
    when:
<<<<<<< HEAD
      branch: [ master ]
=======
      branch: [ main ]
>>>>>>> community/main
    commands: |
      apk add --no-cache shellcheck

      find ./* -type f -name build -o -name post-\* -o -name pre-\* | sed 's/[^[:alnum:]]/\\\\&/g' | xargs shellcheck
