#!/bin/sh -e

./configure \
    --prefix=/usr \
    --disable-static \
    --disable-allstatic \
    --disable-static-libc \
    --enable-shared \
    --libexecdir=/usr/lib

make
make DESTDIR="$1" install
