#!/bin/sh -e

export CFLAGS="$CFLAGS -fPIC"
export CFLAGS="$CFLAGS -DFZ_ENABLE_HTML=0 \
    -DFZ_ENABLE_JPX=0 -DFZ_ENABLE_EPUB=0 \
    -DNO_CJK -DFZ_ENABLE_ICC=0 -DFZ_ENABLE_JS=0"

for p in *.patch; do
    patch -p1 < "$p"
done

make \
    prefix=/usr \
    shared=yes \
    build=release \
    USE_SYSTEM_LIBS=yes \
    USE_SYSTEM_OPENJPEG=no \
    HAVE_X11=no \
    HAVE_GLUT=no \
    install

ln -s libmupdf.so "$1/usr/lib/libmupdf.so.0"
