#!/bin/sh -e

install -Dm644 -t "$1/usr/share/vim/vimfiles/doc"             doc/vundle.txt
install -Dm644 -t "$1/usr/share/vim/vimfiles/autoload"        autoload/vundle.vim
install -Dm644 -t "$1/usr/share/vim/vimfiles/autoload/vundle" autoload/vundle/*.vim
install -Dm644 -t "$1/usr/share/licenses/vundle/LICENSE"     LICENSE-MIT.txt
install -Dm644 -t "$1/usr/share/doc/vundle/README"           README.md
