#!/bin/sh -e

export DESTDIR="$1"

for patch in *.patch; do
    patch -p1 < "$patch"
done

./configure \
    --prefix=/usr \
    --with-terminfo=/usr/share/terminfo \
    --disable-256-color \
    --enable-font-styles \
    --enable-xim \
    --disable-keepscrolling \
    --enable-selectionscrolling \
    --disable-smart-resize \
    --disable-transparency \
    --enable-frills \
    --disable-perl \
    --enable-mousewheel \
    --enable-text-blink \
    --enable-fading \
    --enable-unicode3 \
    --disable-utmp \
    --disable-wtmp \
    --disable-lastlog \
    --enable-xft \
    --enable-combining \
    --disable-pixbuf \
    --enable-startup-notification \
    --disable-afterimage \
    --disable-rxvt-scroll \
    --disable-next-scroll \
    --disable-xterm-scroll \
    --disable-iso14755 \
    --disable-slipwheeling \
    --with-name=rxvt-unicode \
    --enable-pointer-blank \
    --enable-wide-glyphs

make install
