#!/bin/sh -e

export GCC_IGNORE_WERROR=1
export CFLAGS="-march=ivybridge -O3 -ffat-lto-objects -flto=4 "
export FCFLAGS="-march=ivybridge -O3 -ffat-lto-objects -flto=4 "
export FFLAGS="-march=ivybridge -O3 -ffat-lto-objects -flto=4 "
export CXXFLAGS="-march=ivybridge -O3 -ffat-lto-objects -flto=4 "

export DESTDIR="$1"

TMPDIR="$1/tmp"

./configure \
    --prefix=/usr \
    --sysconfdir=/etc \
    --mandir=/usr/share/man \
    --localstatedir=/var \
    --without-xmlto \
    --disable-specs \
    --disable-static

make
make install

# Some X11 packages install to /usr/share.
! [ -d "$1/usr/share/pkgconfig" ] || {
    mkdir -p "$1/usr/lib"
    mv -f "$1/usr/share/pkgconfig" "$1/usr/lib"
}

# We need to keep this around.
! [ -d "$1/usr/share/aclocal" ] || {
    mkdir -p "$TMPDIR"
    mv -f "$1/usr/share/aclocal" "$TMPDIR"
}

# Restore kept directories.
! [ -d "$TMPDIR" ] || {
    mv -f "$TMPDIR/"* "$1/usr/share"
    rm -rf "$TMPDIR"
}
