#!/bin/sh -e

./configure \
    --prefix=/usr \
    --enable-static-libc \
    --disable-shared \
    --enable-allstatic

make
make install

mkdir -p "$1/etc/sv/mdevd"
cp -f mdev.conf "$1/etc"
cp -f mdevd.run  "$1/etc/sv/mdevd/run"
