#!/bin/sh -e

patch -p1 < cmake.patch

cmake -B build \
    -DCMAKE_INSTALL_PREFIX=/usr \
    -DCMAKE_INSTALL_LIBDIR=lib \
    -DCMAKE_BUILD_TYPE=Release 

cmake --build   build
cmake --install build
