#!/bin/sh -e

CFLAGS='-O3 -march=native -pipe'
CXXFLAGS='-O3 -march=native -pipe'

./configure \
    --prefix="/Programs/Musl/$2" \
    --syslibdir="/Programs/Musl/$2/lib" \
    --exec-prefix="/Programs/Musl/$2" \
    --includedir="/Programs/Musl/$2/include" \
    --libdir="/Programs/Musl/$2/lib" \
    --syslibdir="/lib" \
    --disable-shared

make
make install

mkdir -p "$1/Programs/Musl/$2/bin"
ln -s  "$1/Programs/Musl/$2/lib/ld-musl-x86_64.so.1" "$1/Programs/Musl/$2/bin/ldd"

# Fix incorrect symlink to libc.so.
ln -sf libc.so "$1/Programs/Musl/$2/lib/ld-musl-x86_64.so.1"

# Install BSD compatibility headers.
cp -f cdefs.h queue.h tree.h \
    "$1/Programs/Musl/$2/include/sys"

# Install getconf.
"$1/Programs/Musl/$2/bin/musl-gcc" getconf.c -o "$1/Programs/Musl/$2/bin/getconf"
"$1/Programs/Musl/$2/bin/musl-gcc" getent.c  -o "$1/Programs/Musl/$2/bin/getent"
