#!/bin/sh -e

./configure \
    --prefix=/usr \
    --with-default-path=/usr/bin \
    --enable-shared \
    --disable-static \
    --disable-allstatic \
    --disable-static-libc

make
make DESTDIR="$1" install
