#!/bin/sh -e

export LDFLAGS="$LDFLAGS"

cat > config.mak <<EOF
NO_GETTEXT=YesPlease
NO_SVN_TESTS=YesPlease
NO_TCLTK=YesPlease
NO_NSEC=YesPlease
NO_PERL=YesPlease
NO_SYS_POLL_H=1
EOF

./configure \
    --prefix=/usr \
    --libexecdir=/usr/lib \
    ac_cv_lib_curl_curl_global_init=yes \
    ac_cv_snprintf_returns_bogus=no \
    ac_cv_fread_reads_directories=yes

make LIBS="$(curl-config --static-libs) libgit.a reftable/libreftable.a xdiff/lib.a -lz"
make install

cp -Rf man "$1/usr/share/man"
