#!/bin/sh -e

cat > makeinfo <<EOF
#!/bin/sh
printf 'makeinfo (GNU texinfo) 5.2\n'
EOF

chmod +x makeinfo
export PATH="$PATH:$PWD"

./configure \
    --prefix=/ \
    --with-lib-path=/lib \
    --enable-targets=x86_64-linux-gnu \
    --enable-deterministic-archives \
    --disable-gold \
    --enable-lto \
    --enable-ld=default \
    --enable-plugins \
    --disable-multilib \
    --disable-werror \
    --disable-gdb \
    --disable-nls \
    --disable-readline \
    --disable-gprof \
    --disable-gprofng \
    --with-mmap \
    --with-system-zlib

make configure-host
make tooldir=/
make DESTDIR="$1" tooldir=/ install

ln -sf ld.bfd "$1/bin/ld"
