#!/bin/sh -e

sed 's|/lib|/usr/lib|g' Makefile > _
mv -f _ Makefile

make WITH_OBSTACK=musl-obstack WITH_LIBUCONTEXT=1 LINKER_PATH=/lib/ld-musl-x86_64.so.1 LOADER_NAME=ld-linux-x86-64.so.2
make WITH_OBSTACK=musl-obstack WITH_LIBUCONTEXT=1 LINKER_PATH=/lib/ld-musl-x86_64.so.1 LOADER_NAME=ld-linux-x86-64.so.2 install

