#!/bin/sh -e

export DESTDIR="$1"

meson setup \
    -Dprefix=/usr \
    -Ddefault-wallpaper=false \
    -Dzsh-completions=false \
    -Dbash-completions=false \
    -Dfish-completions=false \
    build

ninja -C build
ninja -C build install
