#!/bin/sh -e

export CFLAGS="-march=ivybridge -g1 -O3 -fstack-protector -Wl,-z -Wl,now -Wl,-z -Wl,relro -Wl,-z,max-page-size=0x1000 -fPIC"
export CFLAGS_FOR_TARGET="-march=ivybridge -g1 -O3 -fstack-protector -Wl,-z -Wl,now -Wl,-z -Wl,relro -Wl,-z,max-page-size=0x1000 -fPIC"
export CXXFLAGS="-march=ivybridge -g1 -O3 -Wl,-z,max-page-size=0x1000 -fPIC"
export CXXFLAGS_FOR_TARGET="-march=ivybridge -g1 -O3 -Wl,-z,max-page-size=0x1000 -fPIC"

# Make sure gmp is built with generic options.
cp gcc/gmp/configfsf.guess gcc/gmp/config.guess
cp gcc/gmp/configfsf.sub   gcc/gmp/config.sub

# Use lib not lib64 by default.
sed '/m64=/s/lib64/lib/' gcc/gcc/config/i386/t-linux64 > _
mv -f _ gcc/gcc/config/i386/t-linux64
sed 's/lib64/lib/' gcc/gcc/config/i386/linux64.h > _
mv -f _ gcc/gcc/config/i386/linux64.h

# Build must happen outside of gcc source.
mkdir -p gcc-build
cd gcc-build

# Grab the system's GCC version.
gcc_version=$(gcc -dumpfullversion 2>/dev/null) || gcc_version=null

# Skip the bootstrap process if we are able.
case $2 in "${gcc_version%%.*}"*)
    printf '%s\n' "Minor version difference, disabling bootstrap."
    bootstrap=--disable-bootstrap
esac

../gcc/configure \
    --prefix=/ \
    --disable-multilib \
    --disable-symvers \
    --disable-libmpx \
    --disable-libmudflap \
    --disable-libsanitizer \
    --disable-werror \
    --disable-fixed-point \
    --enable-libstdcxx-pch \
    --disable-nls \
    --enable-checking=release \
    --enable-__cxa_atexit \
    --enable-default-pie \
    --enable-default-ssp \
    --enable-shared \
    --enable-threads \
    --enable-tls \
    --enable-languages=c,c++,fortran,jit --enable-host-shared \
    --without-included-gettext \
    --with-zstd=yes \
    --with-isl=yes \
    --with-system-zlib \
    --build=x86_64-pc-linux-gnu \
    "${bootstrap:---enable-bootstrap}"

    # --libexecdir=/usr/lib \
    # --mandir=/share/man \
    # --infodir=/share/info \

make
make install

# # Save 35MB.
# find "$1" -name libgtkpeer.a  -exec rm -f {} +
# find "$1" -name libgjsmalsa.a -exec rm -f {} +
# find "$1" -name libgij.a      -exec rm -f {} +

ln -sf gcc "$1/bin/cc"
cp -f ../c99 "$1/bin"

# Symlink for LTO.
{
    mkdir -p "$1/lib/bfd-plugins"

    ln -s "/lib/gcc/x86_64-pc-linux-gnu/$2/liblto_plugin.so" \
          "$1/lib/bfd-plugins/liblto_plugin.so"
}
