#!/bin/sh -e

make CC="/Programs/Musl/current/bin/musl-gcc $CFLAGS -static -fPIC $LDFLAGS" bzip2

mkdir -p \
    "$1/Programs/Bzip2/$2/bin" \
    "$1/Programs/Bzip2/$2/lib" \
    "$1/Programs/Bzip2/$2/share/man/man1" \
    "$1/Programs/Bzip2/$2/include"

cp -f \
    bzip2 \
    bzdiff \
    bzgrep \
    bzmore \
    "$1/Programs/Bzip2/$2/bin"

cp -f libbz2.a "$1/Programs/Bzip2/$2/lib"

cp -f bzip2.1 "$1/Programs/Bzip2/$2/share/man/man1"
cp -f bzlib.h "$1/Programs/Bzip2/$2/include"

ln -sf bzip2 "$1/Programs/Bzip2/$2/bin/bunzip2"
ln -sf bzip2 "$1/Programs/Bzip2/$2/bin/bzcat"
