#!/bin/sh -e

./configure \
    --prefix=/usr \
    --libexecdir=/usr/bin \
    --localstatedir=/var \
    --disable-dbus

make
make install

cp -f iwd_passphrase "$1/usr/bin"
mkdir -p "$1/etc/iwd"
cp -f main.conf "$1/etc/iwd"
