#!/bin/sh -e

## Patch configure.ac to compile without libexif.
## On next release this patch can be probably
## deleted
patch -p1 < libexif.patch

autoconf

./configure \
    --prefix=/usr \
    --disable-nls
	
make
make DESTDIR="$1" install
