#!/bin/sh -e

patch -p1 < closefrom-glibc.patch

./configure \
    --prefix=/usr \
    --bindir=/usr/bin \
    --sbindir=/usr/bin \
    --datarootdir=/usr/share \
    --disable-example \
    MOUNT_FUSE_PATH=/usr/bin \
    UDEV_RULES_PATH=/usr/lib/udev

make
make DESTDIR="$1" install
