#!/bin/sh -e

export DESTDIR="$1"

export LDFLAGS="$LDFLAGS -static"

# Removed openssl API used only for leak checks, it's recommended to use sanitizers instead now.
sed '/CRYPTO_mem_ctrl/d' src/ssli_openssl.c > _
mv -f _ src/ssli_openssl.c

cmake -B build \
    -DCMAKE_INSTALL_PREFIX=/usr

cmake --build   build
cmake --install build
