#!/bin/sh -e

patch -p1 < no-perl.patch
patch -p1 < o2_n.patch

cd firmware/regdb
make maintainer-clean
patch -p1 < ../../wireless-regdb-xh.patch
./db2fw.py regulatory.db db.txt
cd $OLDPWD

sed '/<stdlib.h>/a #include <linux/stddef.h>' tools/objtool/arch/x86/decode.c > _
mv -f _ tools/objtool/arch/x86/decode.c

mv firmware/microcode/intel-ucode firmware
mv firmware/regdb/regulatory.db firmware
mv firmware/linux-firmware/iwlwifi-6000g2a-6.ucode firmware

# find . -name 06-3a-09
# find . -name \*6000g2a-6\*
# find . -name regulatory.db

# lspci -k

# make oldconfig
# scripts/kconfig/merge_config.sh -m -n -y .config config.fragments
# scripts/kconfig/merge_config.sh -m -n -y .config config.fragments
# make LSMOD="$(hostname)-modprobed.db" localyesconfig
# scripts/kconfig/merge_config.sh -m -n -y .config config.fragments

make defconfig
# scripts/kconfig/merge_config.sh -m .config clear.config.fragment
# make LSMOD="$(hostname)-modprobed.db" localyesconfig
# scripts/kconfig/merge_config.sh -m .config manual-changes.config.fragment firmware.config.fragment cmdline.config.fragment
scripts/kconfig/merge_config.sh -m .config clear.config.fragment localyesconfig.config.fragment manual-changes.config.fragment firmware.config.fragment cmdline.config.fragment iwd.config.fragment

sed -i "s|KISSBUILDDIRECTORY|$PWD/firmware|" .config

make

install -Dm644 "arch/x86/boot/bzImage" "$1/boot/EFI/BOOT/bootx64.efi"
install -Dm644 System.map "$1/usr/src/linux/System.map"


