#!/bin/sh -e

export DESTDIR="$1"

export C_INCLUDE_PATH="$C_INCLUDE_PATH:$PWD/include"

mkdir include/sys
echo "#include <unistd.h>" > include/sys/unistd.h

meson \
    --prefix=/usr \
    . output

ninja -C output
ninja -C output install
