#!/bin/sh -e

cat > makeinfo <<EOF
#!/bin/sh
printf 'makeinfo (GNU texinfo) 5.2\n'
EOF

chmod +x makeinfo
export PATH="$PATH:$PWD"

gunzip stow.html.gz > ./doc/manual-single.html

./configure \
    --prefix=/

make
make DESTDIR="$1" install
