#!/bin/sh -e

cat >> src/libotutil/otutil.h <<EOF
#ifndef ALLPERMS
#define ALLPERMS (S_ISUID|S_ISGID|S_ISVTX|S_IRWXU|S_IRWXG|S_IRWXO)/* 07777 */
#endif
EOF

./configure \
    --prefix=/usr \
    --sysconfdir=/etc \
    --disable-man \
    --disable-rofiles-fuse \
    --with-soup=no \
    --with-curl=yes

make
make DESTDIR="$1" install
